name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-base:
    uses: phylaxsystems/actions/.github/workflows/rust-base.yaml@odyslam-patch-1
    with:
      rust-channel: 'nightly'
      dind: true
  