name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-base:
    uses: ./.github/workflows/rust-base.yml
    with:
      rust-channel: 'nightly'
      dind: true
